/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	examplecomv1 "github.com/starizard/kube-envoy-controller/pkg/api/example.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEnvoys implements EnvoyInterface
type FakeEnvoys struct {
	Fake *FakeExampleV1
	ns   string
}

var envoysResource = schema.GroupVersionResource{Group: "example.com", Version: "v1", Resource: "envoys"}

var envoysKind = schema.GroupVersionKind{Group: "example.com", Version: "v1", Kind: "Envoy"}

// Get takes name of the envoy, and returns the corresponding envoy object, and an error if there is any.
func (c *FakeEnvoys) Get(name string, options v1.GetOptions) (result *examplecomv1.Envoy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(envoysResource, c.ns, name), &examplecomv1.Envoy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.Envoy), err
}

// List takes label and field selectors, and returns the list of Envoys that match those selectors.
func (c *FakeEnvoys) List(opts v1.ListOptions) (result *examplecomv1.EnvoyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(envoysResource, envoysKind, c.ns, opts), &examplecomv1.EnvoyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &examplecomv1.EnvoyList{ListMeta: obj.(*examplecomv1.EnvoyList).ListMeta}
	for _, item := range obj.(*examplecomv1.EnvoyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested envoys.
func (c *FakeEnvoys) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(envoysResource, c.ns, opts))

}

// Create takes the representation of a envoy and creates it.  Returns the server's representation of the envoy, and an error, if there is any.
func (c *FakeEnvoys) Create(envoy *examplecomv1.Envoy) (result *examplecomv1.Envoy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(envoysResource, c.ns, envoy), &examplecomv1.Envoy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.Envoy), err
}

// Update takes the representation of a envoy and updates it. Returns the server's representation of the envoy, and an error, if there is any.
func (c *FakeEnvoys) Update(envoy *examplecomv1.Envoy) (result *examplecomv1.Envoy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(envoysResource, c.ns, envoy), &examplecomv1.Envoy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.Envoy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEnvoys) UpdateStatus(envoy *examplecomv1.Envoy) (*examplecomv1.Envoy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(envoysResource, "status", c.ns, envoy), &examplecomv1.Envoy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.Envoy), err
}

// Delete takes name of the envoy and deletes it. Returns an error if one occurs.
func (c *FakeEnvoys) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(envoysResource, c.ns, name), &examplecomv1.Envoy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEnvoys) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(envoysResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &examplecomv1.EnvoyList{})
	return err
}

// Patch applies the patch and returns the patched envoy.
func (c *FakeEnvoys) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *examplecomv1.Envoy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(envoysResource, c.ns, name, pt, data, subresources...), &examplecomv1.Envoy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.Envoy), err
}
