/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	examplecomv1 "github.com/starizard/kube-envoy-controller/pkg/api/example.com/v1"
	versioned "github.com/starizard/kube-envoy-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/starizard/kube-envoy-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/starizard/kube-envoy-controller/pkg/client/listers/example.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EnvoyInformer provides access to a shared informer and lister for
// Envoys.
type EnvoyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.EnvoyLister
}

type envoyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEnvoyInformer constructs a new informer for Envoy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEnvoyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEnvoyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEnvoyInformer constructs a new informer for Envoy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEnvoyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1().Envoys(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1().Envoys(namespace).Watch(options)
			},
		},
		&examplecomv1.Envoy{},
		resyncPeriod,
		indexers,
	)
}

func (f *envoyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEnvoyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *envoyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&examplecomv1.Envoy{}, f.defaultInformer)
}

func (f *envoyInformer) Lister() v1.EnvoyLister {
	return v1.NewEnvoyLister(f.Informer().GetIndexer())
}
