apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-cfg-1
  namespace: default
data:
  envoy.yaml: >
    dynamic_resources:
      ads_config:
        api_type: GRPC
        grpc_services:
          envoy_grpc:
            cluster_name: xds_cluster
      cds_config:
        api_config_source:
          api_type: GRPC
          grpc_services:
           envoy_grpc:
             cluster_name: xds_cluster
      lds_config:
        api_config_source:
          api_type: GRPC
          grpc_services:
           envoy_grpc:
             cluster_name: xds_cluster
    node:
      cluster: service_1
      id: test-id
    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout: 1s
        hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 18000
        http2_protocol_options: {}
    admin:
      access_log_path: /tmp/admin_access.log
      profile_path: /tmp/envoy.prof
      address:
        socket_address: { address: 127.0.0.1, port_value: 9901 }