/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/starizard/kube-envoy-controller/pkg/api/example.com/v1"
	scheme "github.com/starizard/kube-envoy-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EnvoysGetter has a method to return a EnvoyInterface.
// A group's client should implement this interface.
type EnvoysGetter interface {
	Envoys(namespace string) EnvoyInterface
}

// EnvoyInterface has methods to work with Envoy resources.
type EnvoyInterface interface {
	Create(*v1.Envoy) (*v1.Envoy, error)
	Update(*v1.Envoy) (*v1.Envoy, error)
	UpdateStatus(*v1.Envoy) (*v1.Envoy, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Envoy, error)
	List(opts metav1.ListOptions) (*v1.EnvoyList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Envoy, err error)
	EnvoyExpansion
}

// envoys implements EnvoyInterface
type envoys struct {
	client rest.Interface
	ns     string
}

// newEnvoys returns a Envoys
func newEnvoys(c *ExampleV1Client, namespace string) *envoys {
	return &envoys{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the envoy, and returns the corresponding envoy object, and an error if there is any.
func (c *envoys) Get(name string, options metav1.GetOptions) (result *v1.Envoy, err error) {
	result = &v1.Envoy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("envoys").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Envoys that match those selectors.
func (c *envoys) List(opts metav1.ListOptions) (result *v1.EnvoyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EnvoyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("envoys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested envoys.
func (c *envoys) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("envoys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a envoy and creates it.  Returns the server's representation of the envoy, and an error, if there is any.
func (c *envoys) Create(envoy *v1.Envoy) (result *v1.Envoy, err error) {
	result = &v1.Envoy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("envoys").
		Body(envoy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a envoy and updates it. Returns the server's representation of the envoy, and an error, if there is any.
func (c *envoys) Update(envoy *v1.Envoy) (result *v1.Envoy, err error) {
	result = &v1.Envoy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("envoys").
		Name(envoy.Name).
		Body(envoy).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *envoys) UpdateStatus(envoy *v1.Envoy) (result *v1.Envoy, err error) {
	result = &v1.Envoy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("envoys").
		Name(envoy.Name).
		SubResource("status").
		Body(envoy).
		Do().
		Into(result)
	return
}

// Delete takes name of the envoy and deletes it. Returns an error if one occurs.
func (c *envoys) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("envoys").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *envoys) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("envoys").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched envoy.
func (c *envoys) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Envoy, err error) {
	result = &v1.Envoy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("envoys").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
